Added FortranFixed for fixed form input.

diff --git a/tests/D-TEC/Makefile b/tests/D-TEC/Makefile
--- a/tests/D-TEC/Makefile
+++ b/tests/D-TEC/Makefile
@@ -5,14 +5,23 @@ all : check
 $(SYNTAX)/Fortran.tbl :
 	cd $(SYNTAX) ; make ; cd -
 
-check : $(SYNTAX)/Fortran.tbl
+$(SYNTAX)/FortranFixed.tbl :
+	cd $(SYNTAX) ; make ; cd -
+
+check : $(SYNTAX)/Fortran.tbl $(SYNTAX)/FortranFixed.tbl
 	@for file in *.f90 ; do \
            echo "Running test $$file"; \
            sglri -p $(SYNTAX)/Fortran.tbl -i $$file -o $$file.ast; \
            if test $$? != 0 ; then \
              echo $$file "		FAILED!"; \
            fi; \
-           pp-aterm -i $$file.ast -o $$file.ast.aterm; \
+        done;
+	@for file in *.f ; do \
+           echo "Running test $$file"; \
+           sglri -p $(SYNTAX)/FortranFixed.tbl -i $$file -o $$file.ast; \
+           if test $$? != 0 ; then \
+             echo $$file "		FAILED!"; \
+           fi; \
         done;
 
 junk :
