Replaced check-all by check and added targets for check-f77; check-f90; check-f08; and check-fxx.

diff --git a/tests/rule-tests/pp/Makefile b/tests/rule-tests/pp/Makefile
--- a/tests/rule-tests/pp/Makefile
+++ b/tests/rule-tests/pp/Makefile
@@ -9,16 +9,7 @@ TO_FAST = $(TRANS_DIR)/ofp2fast
 TO_PP   = $(TRANS_DIR)/fast2pp
 PP      = ../../../fortran/pp/Fortran.pp
 
-CHECK_LIST = R1101a.f90 R1101b.f90 R1101c.f90 R1101d.f90 R1101e.f90 R1101f.f90 R1101g.f90\
-             R404.f90 R426.fxx R427.fxx R452.f90 \
-             R524.f90 R526.f90 \
-             R611.f90 R620.f90 \
-             R701.f90 R702.fxx R704.f90 R705.f90 R706.f90 R710.f90 R713.f90 R719.f90 \
-             R720.f90 R721.f90 R722.fxx R723.fxx R733.fxx \
-             R807.f90 R854.f90 \
-             R1001.f90 \
-             R1203.f90 R1206.f90 R1209.f90 R1210.f90 R1214.f90 R1218.f90 R1220.fxx \
-             R1234.f90 R1237.fxx
+CHECK_LIST = R1101a.f90
 
 all : check
 
@@ -37,7 +28,7 @@ fast : $(TBL)
 	   sglri -p $(TBL) -i $$file | $(TO_FAST) | pp-aterm -o tmp-fast/$$file.aterm; \
         done;
 
-check-all : $(TBL)
+check : $(TBL)
 	@for file in *.f90 ; do \
            echo "Running test $$file"; \
 	   sglri -p $(TBL) -i $$file | $(TO_FAST) | $(TO_PP) | ast2text -p $(PP) -o tmp/$$file; \
@@ -75,7 +66,55 @@ check-all : $(TBL)
            fi; \
         done;
 
-check : $(TBL)
+check-f90 : $(TBL)
+	@for file in *.f90 ; do \
+           echo "Running test $$file"; \
+	   sglri -p $(TBL) -i $$file | $(TO_FAST) | $(TO_PP) | ast2text -p $(PP) -o tmp/$$file; \
+           diff $$file tmp/$$file; \
+           if test $$? != 0 ; then \
+             echo $$file "		FAILED!"; \
+           fi; \
+           $(FC) -c tmp/$$file -o tmp/$$file.o; \
+           if test $$? != 0 ; then \
+             echo $$file "		FAILED!"; \
+           fi; \
+        done;
+
+check-f77 : $(TBL)
+	@for file in *.f77 ; do \
+           echo "Running test $$file"; \
+	   sglri -p $(TBL) -i $$file | $(TO_FAST) | $(TO_PP) | ast2text -p $(PP) -o tmp/$$file; \
+           diff $$file tmp/$$file; \
+           if test $$? != 0 ; then \
+             echo $$file "		FAILED!"; \
+           fi; \
+           $(FC) -c tmp/$$file -o tmp/$$file.o; \
+           if test $$? != 0 ; then \
+             echo $$file "		FAILED!"; \
+           fi; \
+        done;
+
+check-f08 : $(TBL)
+	@for file in *.f08 ; do \
+           echo "Running test $$file"; \
+	   sglri -p $(TBL) -i $$file | $(TO_FAST) | $(TO_PP) | ast2text -p $(PP) -o tmp/$$file; \
+           diff $$file tmp/$$file; \
+           if test $$? != 0 ; then \
+             echo $$file "		FAILED!"; \
+           fi; \
+        done;
+
+check-fxx : $(TBL)
+	@for file in *.fxx ; do \
+           echo "Running test $$file"; \
+	   sglri -p $(TBL) -i $$file | $(TO_FAST) | $(TO_PP) | ast2text -p $(PP) -o tmp/$$file; \
+           diff $$file tmp/$$file; \
+           if test $$? != 0 ; then \
+             echo $$file "		FAILED!"; \
+           fi; \
+        done;
+
+check-list : $(TBL)
 	@for file in $(CHECK_LIST) ; do \
            echo "Running test $$file"; \
 	   sglri -p $(TBL) -i $$file | $(TO_FAST) | $(TO_PP) | ast2text -p $(PP) -o tmp/$$file; \
