Completed syntax additions for Fortran 2015.
  * from TS 18508 "Addtional Parallel Features in Fortran" WG5/N2007

diff --git a/tests/rule-tests/Makefile b/tests/rule-tests/Makefile
--- a/tests/rule-tests/Makefile
+++ b/tests/rule-tests/Makefile
@@ -29,6 +29,25 @@ check : $(SYNTAX)/Fortran.tbl
            fi; \
         done;
 
+chck : $(SYNTAX)/Fortran.tbl
+	@for file in R*.f90 R*.fxx R*.f08 ; do \
+           echo "Running test $$file"; \
+           $(SGLRI) -p $(SYNTAX)/Fortran.tbl -i $$file -o $$file.ast; \
+           if test $$? != 0 ; then \
+             echo $$file "		Parsing FAILED!"; \
+           fi; \
+           pp-aterm -i $$file.ast -o $$file.ast.trm; \
+           diff $$file.ast.trm ast-aterms/$$file.ast.trm; \
+           if test $$? != 0 ; then \
+             echo $$file "		FAILED!"; \
+            fi; \
+           $(TRANS)/ofp2fast -i $$file.ast | pp-aterm -o $$file.fast.trm; \
+           diff $$file.fast.trm ast-aterms/$$file.fast.trm; \
+           if test $$? != 0 ; then \
+             echo $$file "		FAST FAILED!"; \
+            fi; \
+        done;
+
 junk : $(SYNTAX)/Fortran.tbl  $(TRANS)/ofp-simplify
 	$(SGLRI) -p $(SYNTAX)/Fortran.tbl -i junk.f90 | $(TRANS)/ofp-simplify | pp-aterm
 
