Added check of *.for fixed form files.

diff --git a/tests/issues/Makefile b/tests/issues/Makefile
--- a/tests/issues/Makefile
+++ b/tests/issues/Makefile
@@ -4,10 +4,13 @@ SYNTAX_DIR = ../../fortran/syntax
 TRANS_DIR  = ../../fortran/trans
 
 TBL     = $(SYNTAX_DIR)/Fortran.tbl
+TBL_F   = $(SYNTAX_DIR)/FixedForm.tbl
 TO_SIM  = $(TRANS_DIR)/ofp-simplify
 TO_FAST = $(TRANS_DIR)/ofp2fast
+TO_FREE = $(TRANS_DIR)/fixed-to-free
 TO_PP   = $(TRANS_DIR)/fast2pp
 PP      = ../../fortran/pp/Fortran.pp
+PP_F    = ../../fortran/pp/FreeForm.pp
 
 all : check
 
@@ -23,6 +26,13 @@ check : $(TBL)
 	@for file in *.f90.no-diff ; do \
            echo "Running test $$file"; \
 	   sglri -p $(TBL) -i $$file | $(TO_FAST) | $(TO_PP) | ast2text -p $(PP) -o tmp/$$file.f90; \
+           if test $$? != 0 ; then \
+             echo $$file "		FAILED!"; \
+           fi; \
+        done;
+	@for file in *.for.no-diff ; do \
+           echo "Running test $$file"; \
+	   sglri -p $(TBL_F) -i $$file | $(TO_FREE) | ast2text -p $(PP_F) | sglri -p $(TBL) | $(TO_FAST) | $(TO_PP) | ast2text -p $(PP) -o tmp/$$file.f90; \
            if test $$? != 0 ; then \
              echo $$file "		FAILED!"; \
            fi; \
