Added testing of files (*.f90.no-diff) for which the unparsed file isn't expected to match the original.

diff --git a/tests/issues/Makefile b/tests/issues/Makefile
--- a/tests/issues/Makefile
+++ b/tests/issues/Makefile
@@ -20,6 +20,13 @@ check : $(TBL)
              echo $$file "		FAILED!"; \
            fi; \
         done;
+	@for file in *.f90.no-diff ; do \
+           echo "Running test $$file"; \
+	   sglri -p $(TBL) -i $$file | $(TO_FAST) | $(TO_PP) | ast2text -p $(PP) -o tmp/$$file.f90; \
+           if test $$? != 0 ; then \
+             echo $$file "		FAILED!"; \
+           fi; \
+        done;
 
 check-f90 : $(TBL)
 	@for file in *.f90 ; do \
